// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// // "use client"
// // import { useEffect } from "react"
// // import { useThemeStore, initTheme } from "@/stores/themeStore"

// // export default function RootLayout({ children }: { children: React.ReactNode }) {
// //   const toggleTheme = useThemeStore((state) => state.toggle)

// //   useEffect(() => {
// //     initTheme()
// //   }, [])

// //   return (
// //     <html lang="en">
// //       <body className="bg-white text-black dark:bg-gray-900 dark:text-white transition-colors duration-300">
// //         {children}

// //         {/* دکمه سوییچ تم */}
// //         <button
// //           onClick={toggleTheme}
// //           className="fixed bottom-4 right-4 p-2 rounded bg-gray-200 dark:bg-gray-700 text-black dark:text-white"
// //         >
// //           Toggle Theme
// //         </button>
// //       </body>
// //     </html>
// //   )
// // }
import Footer from '@/components/Footer';
import './globals.css';
import { ThemeProvider } from '@/components/themProvider';
// app/layout.tsx
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Stopwatch",
  description: "A beautiful, minimal and fast stopwatch app",
  icons: {
    icon: "/icons/favicon.jpg",
  },
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}